services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pyra
      POSTGRES_PASSWORD: pyra
      POSTGRES_DB: pyra_dev
    volumes:
      - pyra-db:/var/lib/postgresql

  db-test:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: pyra_test
      POSTGRES_PASSWORD: pyra_test
      POSTGRES_DB: pyra_test
    volumes:
      - pyra-db-test:/var/lib/postgresql

volumes:
  pyra-db:
  pyra-db-test:
